### ISSUE TITLE
"No relevant migrations to run. Exiting..." migrating down, doesn't find migrations to run.

### ISSUE THREAD

**Issue by konradwww** [WellingGuzman/Migrations#5]
PHP Version: 7.1.14
MySQL: 5.7

https://github.com/WellingGuzman/Migrations/blob/3f0f3a1eb7739b2d903dea8d53ca2d294edc654b/lib/Ruckusing/Util/Migrator.php#L136

here quickfix:

```
if ($direction == 'up') {
    $start = $key;
}
```

**Comment by WellingGuzman** [comment]
Thanks @konradwww, but I have abandoned this repo and it won't accept any fixes unless is a critical issue with Directus migrations.

**Comment by konradwww** [comment]
I'am using this library in Directus ver. 6.4.8, right now there comes error if I want to migrate down my custom migration.

**Comment by WellingGuzman** [comment]
Hey @konradwww As I cannot test this anymore you are welcome to open a PR, or even better fork it, but I cannot promise much from there.
